variables:
  lldbBuildId: 993
  lldbBuildProject: 'llvm'
  lldbBuildPipeline: 'llvm-project'
  rustcVersion: 'nightly-2019-10-15'
  runTests: true

  setenvLinux: |
      true
  setenvOSX: |
      export PATH=$HOME/.cargo/bin:$PATH
      export PYTHON_SYS_EXECUTABLE=/usr/bin/python2.7
  setenvWindows: |
      set PATH=%USERPROFILE%\.cargo\bin;%PATH%
      set PYTHONHOME=%USEPYTHONVERSION_PYTHONLOCATION%
      set PYTHONPATH=%PYTHONHOME%\Lib;%PYTHONHOME%\DLLs

########################################################################################################################

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

  container:
    image: 'vadimcn/linux-builder:latest'
    options: --privileged

  steps:

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project:  $(lldbBuildProject)
      pipeline: $(lldbBuildPipeline)
      buildId:  $(lldbBuildId)
      buildVersionToDownload: specific
      downloadType: single
      artifactName: 'lldb--x86_64-unknown-linux-gnu'
      itemPattern: 'lldb--x86_64-unknown-linux-gnu/lldb--x86_64-unknown-linux-gnu.zip'
      downloadPath: '$(Agent.BuildDirectory)/D'
    displayName: 'Download LLDB'

  - script: |
      $(setenvLinux)
      echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
      unzip $(Agent.BuildDirectory)/D/lldb--x86_64-unknown-linux-gnu/lldb--x86_64-unknown-linux-gnu.zip -d $(Agent.BuildDirectory)/D/lldb

      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo\
            -DLLDB_ROOT=$(Agent.BuildDirectory)/D/lldb\
            ..
    displayName: 'Configure'

  - script: |
      $(setenvLinux)
      cmake --build build --target vsix_portable
      cmake -E copy build/vscode-lldb-portable.vsix $(Build.ArtifactStagingDirectory)/vscode-lldb-portable.vsix
      cmake --build build --target vsix_full
      cmake -E copy build/vscode-lldb-full.vsix $(Build.ArtifactStagingDirectory)/vscode-lldb-x86_64-linux.vsix
      cmake -E copy build/package.json $(Build.ArtifactStagingDirectory)/package.json
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'vscode-lldb'

  - script: |
      $(setenvLinux)
      cmake --build build --target tests
      cd build
      ctest --output-on-failure -R "native"
    displayName: 'Test native'
    condition: variables.runTests

  - script: |
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(Agent.BuildDirectory)
    displayName: 'On Failure'
    condition: failed()

########################################################################################################################

- job: Linux_aarch64
  pool:
    vmImage: 'Ubuntu 16.04'

  container:
    image: 'vadimcn/linux-builder:latest'
    options: --privileged

  steps:

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project:  $(lldbBuildProject)
      pipeline: $(lldbBuildPipeline)
      buildId:  $(lldbBuildId)
      buildVersionToDownload: specific
      downloadType: single
      artifactName: 'lldb--aarch64-unknown-linux-gnu'
      itemPattern: 'lldb--aarch64-unknown-linux-gnu/lldb--aarch64-unknown-linux-gnu.zip'
      downloadPath: '$(Agent.BuildDirectory)/D'
    displayName: 'Download LLDB'

  - script: |
      $(setenvLinux)
      unzip $(Agent.BuildDirectory)/D/lldb--aarch64-unknown-linux-gnu/lldb--aarch64-unknown-linux-gnu.zip -d $(Agent.BuildDirectory)/D/lldb
      echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo\
            -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-aarch64-unknown-linux-gnu.cmake\
            -DLLDB_ROOT=$(Agent.BuildDirectory)/D/lldb\
            ..
    displayName: 'Configure'

  - script: |
      $(setenvLinux)
      cmake --build build --target vsix_portable
      cmake -E copy build/vscode-lldb-portable.vsix $(Build.ArtifactStagingDirectory)/vscode-lldb-portable.vsix
      cmake --build build --target vsix_full
      cmake -E copy build/vscode-lldb-full.vsix $(Build.ArtifactStagingDirectory)/vscode-lldb-aarch64-linux.vsix
      cmake -E copy build/package.json $(Build.ArtifactStagingDirectory)/package.json
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'vscode-lldb'

  # - script: |
  #     $(setenvLinux)
  #     cmake --build build --target tests
  #     cd build
  #     ctest --output-on-failure -R "native"
  #   displayName: 'Test'
  #   condition: variables.runTests

  - script: |
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(Agent.BuildDirectory)
    displayName: 'On Failure'
    condition: failed()

########################################################################################################################

- job: OSX
  pool:
    vmImage: 'macOS 10.13'

  steps:

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project:  $(lldbBuildProject)
      pipeline: $(lldbBuildPipeline)
      buildId:  $(lldbBuildId)
      buildVersionToDownload: specific
      downloadType: single
      artifactName: 'lldb--x86_64-apple-darwin'
      itemPattern: 'lldb--x86_64-apple-darwin/lldb--x86_64-apple-darwin.zip'
      downloadPath: '$(Agent.BuildDirectory)/D'
    displayName: 'Download LLDB'

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -v -y --profile minimal --default-toolchain none
      source $HOME/.cargo/env
      rustup toolchain install $(rustcVersion)-x86_64-apple-darwin
      rustup default $(rustcVersion)
      rustup show
    displayName: 'Install Rust'

  - script: |
      $(setenvOSX)
      unzip $(Agent.BuildDirectory)/D/lldb--x86_64-apple-darwin/lldb--x86_64-apple-darwin.zip -d $(Agent.BuildDirectory)/D/lldb

      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo\
            -DLLDB_ROOT=$(Agent.BuildDirectory)/D/lldb\
            ..
    displayName: 'CMake configure'

  - script: |
      $(setenvOSX)
      cmake --build build --target vsix_full
      cmake -E copy build/vscode-lldb-full.vsix $(Build.ArtifactStagingDirectory)/vscode-lldb-x86_64-darwin.vsix
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'vscode-lldb'

  - script: |
      $(setenvOSX)
      cmake --build build --target tests
      cd build
      ctest --output-on-failure -R "native"
    displayName: 'Test native'
    condition: variables.runTests

  - script: |
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(Agent.BuildDirectory)
    displayName: 'On Failure'
    condition: failed()

 ########################################################################################################################

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project:  $(lldbBuildProject)
      pipeline: $(lldbBuildPipeline)
      buildId:  $(lldbBuildId)
      buildVersionToDownload: specific
      downloadType: single
      artifactName: 'lldb--x86_64-pc-windows-msvc'
      itemPattern: 'lldb--x86_64-pc-windows-msvc/lldb--x86_64-pc-windows-msvc.zip'
      downloadPath: '$(Agent.BuildDirectory)/D'
    displayName: 'Download LLDB'

  - task: BatchScript@1
    inputs:
      filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
      arguments: -arch=amd64 -host_arch=amd64
      modifyEnvironment: true
    displayName: VsDevCmd

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -v -y --profile minimal --default-toolchain none
      set PATH=%USERPROFILE%\.cargo\bin;%PATH%
      rustup toolchain install $(rustcVersion)-x86_64-pc-windows-gnu
      rustup default $(rustcVersion)-x86_64-pc-windows-gnu
      rustup target add x86_64-pc-windows-msvc
      rustup show
    displayName: 'Install Rust'

  - script: |
      choco install ninja
      choco install zip
      unzip $(Agent.BuildDirectory)/D/lldb--x86_64-pc-windows-msvc/lldb--x86_64-pc-windows-msvc.zip -d $(Agent.BuildDirectory)/D/lldb
    displayName: 'Install other'

  - script: |
      $(setenvWindows)
      mkdir build
      cd build
      cmake -GNinja^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo^
            -DLLDB_ROOT=$(Agent.BuildDirectory)\D\lldb^
            -DCMAKE_C_COMPILER=cl^
            -DCMAKE_CXX_COMPILER=cl^
            ..
    displayName: 'CMake configure'

  - script: |
      $(setenvWindows)
      cmake --build build --target vsix_full
      cmake -E copy build/vscode-lldb-full.vsix $(Build.ArtifactStagingDirectory)/vscode-lldb-x86_64-windows.vsix
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'vscode-lldb'

  - script: |
      $(setenvWindows)
      cmake --build build --target tests
      cd build
      ctest --output-on-failure -R "native"
    displayName: 'Test native'
    condition: variables.runTests

  - script: |
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(Agent.BuildDirectory)
    displayName: 'On Failure'
    condition: failed()
