[build]
target-dir = "@CMAKE_CURRENT_BINARY_DIR@"

[env]
CC_@LLVM_TRIPLE@ = "@CMAKE_C_COMPILER@"
CXX_@LLVM_TRIPLE@ = "@CMAKE_CXX_COMPILER@"
CFLAGS_@LLVM_TRIPLE@ = "@CMAKE_C_FLAGS@"
CXXFLAGS_@LLVM_TRIPLE@ = "@CMAKE_CXX_FLAGS@"
CODELLDB_LIB_PATH = "@CMAKE_CURRENT_BINARY_DIR@/lldb/bin;@CMAKE_CURRENT_BINARY_DIR@/lldb/lib"
