[package]
name = "codelldb"
version = "1.0.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.11"
clap = "2.33.0"
cpython = { version = "0.2.1", default-features = false }
crossterm = "0.9.6"
env_logger = "0.6.2"
failure = "0.1.5"
failure_derive = "0.1.5"
futures = "0.1.28"
lazy_static = "1.3.0"
libc = "0.2.59"
lldb = { path = "deps/lldb" }
log = "0.4.7"
raw_debug_protocol = { package = "debug-protocol", path = "deps/debug-protocol" }
regex = "1.1.9"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
superslice = "1.0.0"
tokio = "0.1.22"

[features]
default = ["python2"]
python2 = ["cpython/python27-sys"]
python3 = ["cpython/python3-sys"]

[lib]
crate-type = ["cdylib"]
