[package]
name = "codelldb_python"
version = "0.1.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.2"
lldb = { path = "../lldb" }
log = "0.4.7"

[[example]]
name = "codelldb_python"
path = "src/impl.rs"
crate-type = ["cdylib"]
