[package]
name = "python-impl"
version = "0.1.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.2"
log = "0.4.7"
lldb = { path = "../lldb" }
interface = { package = "python-interface", path = "../python-interface" }

[lib]
name = "codelldb_python"
crate-type = ["cdylib"]

[features]
weak-linkage = ["lldb/weak-linkage"]
